#!/usr/bin/env bash
# Copyright (c) 2024 Pekka Jääskeläinen / Intel Finland Oy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# A script to test the parallel.bc output using LLVM's FileCheck.
#
# Usage:
#
#   run-and-check-llvm-ir FILECHECK LLVM_DIS TEST_NAME CHECK_FILE... -- CMD [CMD_ARGS...]
#
# Where:
#
# - TEST_NAME is a test name and used for test inputs and check logs.
#
# - FILECHECK is a path to LLVM's FileCheck tool.
#
# - LLVM_DIS is a path to llvm-dis tool.
#
# - CHECK_FILES... is one or more paths to check-files passed to FILECHECK.
#
# - '--' separates the CHECK_FILES... list and the CMD command
#
# - CMD is a test command to be run followed by its optional arguments.
#
# It then runs the given OpenCL application, letting it dump the final
# vectorized work-group function in parallel.bc, which is then checked using
# LLVM's FileCheck with the verification checks read from the given file.
# This thus works only for cases when the application compiles and launches
# a single kernel with a single local size. No error checking / user
# friendliness is done by the script.

LLVM_FILECHECK=$1
LLVM_DIS=$2
TEST_NAME=$3
shift 3

CHECK_FILE_LIST=()
while [ "$1" !=  "--" ]; do
    CHECK_FILE_LIST+=("$1")
    shift 1
done
shift 1 # consume --

# Don't allow a mistake of missing out check-files turned into test pass.
[ ${#CHECK_FILE_LIST[@]} -ne 0 ] || {
    echo "error: no check-files given."
    exit 2
}

APP_CMD=$@

export POCL_KERNEL_CACHE=1
export POCL_CACHE_DIR=$(mktemp -d /tmp/pocl-lit-test-XXXXXXXX)
export POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES=1

# Modify the test name to be path friendly.
TEST_NAME=${TEST_NAME////-} # replace all '/' to '-'.

$APP_CMD
RET=$?
if [ $RET -ne 0 ]; then
  exit $RET
fi

# sort -r ensures we dump all the BC files in a defined order (the specialized
# versions first) so we can inspect the specialized WG(s) as well as the
# generic one in known positions in the output.
BC_FILES=$(find $POCL_CACHE_DIR -name parallel.bc|sort -r)
FILE_CHECK_INPUT=${PWD}/${TEST_NAME}-ir-check-input.ll

> $FILE_CHECK_INPUT
for BC_FILE in $BC_FILES
do
   echo "; $BC_FILE" >> $FILE_CHECK_INPUT
   $LLVM_DIS $BC_FILE -o - >> $FILE_CHECK_INPUT
done

CHECK_OUTPUT_LIST=()
for CHECK_FILE in ${CHECK_FILE_LIST[@]}; do
    CHECK_FILE_BASENAME=$(basename $CHECK_FILE)
    CHECK_OUTPUT=${PWD}/${TEST_NAME}-${CHECK_FILE_BASENAME}.log

    echo "; check-file: '$CHECK_FILE'" > $CHECK_OUTPUT
    $LLVM_FILECHECK --input-file=$FILE_CHECK_INPUT $CHECK_FILE >>$CHECK_OUTPUT 2>&1
    RET=$?
    [ $RET -eq 0 ] && break;

    CHECK_OUTPUT_LIST+=(${CHECK_OUTPUT})
done

trap 'rm -fr $POCL_CACHE_DIR' EXIT

if test $RET -eq 0;
then
    echo "LLVM IR checks OK."
    exit 0
else
    echo "FAIL: none of the check-files passed!"
    cat $FILE_CHECK_INPUT
    echo "note: IR used in file-checks: $FILE_CHECK_INPUT"
    echo "note: file-check logs are written in:"
    for CHECK_OUTPUT in ${CHECK_OUTPUT_LIST[@]}; do
	echo "  ${CHECK_OUTPUT}"
    done
    exit 1
fi
