# adapted from https://github.com/mattsta/cmake-cpu-detect
# Copyright 2019-2021 Matt Stancliff <matt@genges.com>
# Licensed under the Apache License, Version 2.0 (the "License");

# modifications:
# removed feature detection by CPU feature lists (they were outdated)
# removed build flag parsing, instead we either take LLC_HOST_CPU
# if defined, or fallback to -march=native

# generated by parsing clang X86Target.def CPU definitions
include(CheckCSourceCompiles)

# Yes, this function looks WEIRD because it has 100% duplicated behavior
# because CMake aggressively caches the results of feature detection.
#
# If we are cross-compiling against architectures, CMake will _never_ run
# the feature detection a second time even if we change all our compile flags.
#
# So, we ONLY run feature detection if we are using "march=native".
# If not using "march=native", parse cflags to check the arch for compilation.
#
# CPU features are based on our knowledge of compiler<->cpu interactions
# as obtained from clang's description of CPU features inside X86Target.def.
#
# Feature detection is looking at the defines you'd find just by using:
# > clang -march=native -dM -E - < /dev/null
function(genCPUFeatures RESULT_PREFIX)

message("[${RESULT_PREFIX}] flags: ${genCPUFeaturesCachedFlags_${RESULT_PREFIX}}")

if(LLC_HOST_CPU)
  set(CMAKE_REQUIRED_FLAGS "-march=${LLC_HOST_CPU}")
else()
  set(CMAKE_REQUIRED_FLAGS "-march=native")
endif()

check_c_source_compiles("
#ifndef __AES__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AES)
set(${RESULT_PREFIX}_AES ${${RESULT_PREFIX}_FEATURE_AES} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX)
set(${RESULT_PREFIX}_AVX ${${RESULT_PREFIX}_FEATURE_AVX} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX2__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX2)
set(${RESULT_PREFIX}_AVX2 ${${RESULT_PREFIX}_FEATURE_AVX2} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX5124FMAPS__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512BF16)
set(${RESULT_PREFIX}_AVX512BF16 ${${RESULT_PREFIX}_FEATURE_AVX512BF16} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512BITALG__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512BITALG)
set(${RESULT_PREFIX}_AVX512BITALG ${${RESULT_PREFIX}_FEATURE_AVX512BITALG} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512BW__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512BW)
set(${RESULT_PREFIX}_AVX512BW ${${RESULT_PREFIX}_FEATURE_AVX512BW} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512CD__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512CD)
set(${RESULT_PREFIX}_AVX512CD ${${RESULT_PREFIX}_FEATURE_AVX512CD} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512DQ__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512DQ)
set(${RESULT_PREFIX}_AVX512DQ ${${RESULT_PREFIX}_FEATURE_AVX512DQ} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512ER__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512ER)
set(${RESULT_PREFIX}_AVX512ER ${${RESULT_PREFIX}_FEATURE_AVX512ER} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512F__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512F)
set(${RESULT_PREFIX}_AVX512F ${${RESULT_PREFIX}_FEATURE_AVX512F} PARENT_SCOPE)
set(${RESULT_PREFIX}_AVX512 ${RESULT_PREFIX}_FEATURE_AVX512F PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512IFMA__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512IFMA)
set(${RESULT_PREFIX}_AVX512IFMA ${${RESULT_PREFIX}_FEATURE_AVX512IFMA} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512PF__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512PF)
set(${RESULT_PREFIX}_AVX512PF ${${RESULT_PREFIX}_FEATURE_AVX512PF} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512VBMI__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512VBMI)
set(${RESULT_PREFIX}_AVX512VBMI ${${RESULT_PREFIX}_FEATURE_AVX512VBMI} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512VBMI2__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512VBMI2)
set(${RESULT_PREFIX}_AVX512VBMI2 ${${RESULT_PREFIX}_FEATURE_AVX512VBMI2} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512VL__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512VL)
set(${RESULT_PREFIX}_AVX512VL ${${RESULT_PREFIX}_FEATURE_AVX512VL} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512VNNI__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512VNNI)
set(${RESULT_PREFIX}_AVX512VNNI ${${RESULT_PREFIX}_FEATURE_AVX512VNNI} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __AVX512VPOPCNTDQ__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_AVX512VPOPCNTDQ)
set(${RESULT_PREFIX}_AVX512VPOPCNTDQ ${${RESULT_PREFIX}_FEATURE_AVX512VPOPCNTDQ} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __BMI__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_BMI)
set(${RESULT_PREFIX}_BMI ${${RESULT_PREFIX}_FEATURE_BMI} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __BMI2__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_BMI2)
set(${RESULT_PREFIX}_BMI2 ${${RESULT_PREFIX}_FEATURE_BMI2} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __CMOV__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_CMOV)
set(${RESULT_PREFIX}_CMOV ${${RESULT_PREFIX}_FEATURE_CMOV} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __FMA__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_FMA)
set(${RESULT_PREFIX}_FMA ${${RESULT_PREFIX}_FEATURE_FMA} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __FMA4__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_FMA4)
set(${RESULT_PREFIX}_FMA4 ${${RESULT_PREFIX}_FEATURE_FMA4} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __GFNI__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_GFNI)
set(${RESULT_PREFIX}_GFNI ${${RESULT_PREFIX}_FEATURE_GFNI} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __MMX__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_MMX)
set(${RESULT_PREFIX}_MMX ${${RESULT_PREFIX}_FEATURE_MMX} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __PCLMUL__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_PCLMUL)
set(${RESULT_PREFIX}_PCLMUL ${${RESULT_PREFIX}_FEATURE_PCLMUL} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __POPCNT__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_POPCNT)
set(${RESULT_PREFIX}_POPCNT ${${RESULT_PREFIX}_FEATURE_POPCNT} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __SSE__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_SSE)
set(${RESULT_PREFIX}_SSE ${${RESULT_PREFIX}_FEATURE_SSE} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __SSE2__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_SSE2)
set(${RESULT_PREFIX}_SSE2 ${${RESULT_PREFIX}_FEATURE_SSE2} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __SSE3__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_SSE3)
set(${RESULT_PREFIX}_SSE3 ${${RESULT_PREFIX}_FEATURE_SSE3} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __SSE4_1__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_SSE4_1)
set(${RESULT_PREFIX}_SSE4_1 ${${RESULT_PREFIX}_FEATURE_SSE4_1} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __SSE4_2__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_SSE4_2)
set(${RESULT_PREFIX}_SSE4_2 ${${RESULT_PREFIX}_FEATURE_SSE4_2} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __SSE4_A__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_SSE4_A)
set(${RESULT_PREFIX}_SSE4_A ${${RESULT_PREFIX}_FEATURE_SSE4_A} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __SSSE3__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_SSSE3)
set(${RESULT_PREFIX}_SSSE3 ${${RESULT_PREFIX}_FEATURE_SSSE3} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __VPCLMULQDQ__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_VPCLMULQDQ)
set(${RESULT_PREFIX}_VPCLMULQDQ ${${RESULT_PREFIX}_FEATURE_VPCLMULQDQ} PARENT_SCOPE)

check_c_source_compiles("
#ifndef __XOP__
#error not supported
#endif

int main(void) {
    return 0;
}" ${RESULT_PREFIX}_FEATURE_XOP)
set(${RESULT_PREFIX}_XOP ${${RESULT_PREFIX}_FEATURE_XOP} PARENT_SCOPE)

endfunction()
